<MainLayout>:
    GameLogic:
        BoxLayout:
            orientation: 'vertical'
            LogicBlocksGridLayout:
            #GridLayout:
            #    id: logic_blocks_grid
            #    cols: 6
            GridLayout:
                background_color: [1.0,0.0,0.0,1.0]
                id: logic_field_grid
                cols: 6
                rows: 6
    PlayingField:

<LogicBlocksGridLayout>:
    cols: 6


<PlayingField>:
    cols: 10
    rows: 10
